print("Tabela verdade do AND")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("---------------------")

print("Tabela verdade do OR")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print("---------------------")

print("Tabela verdade do XOR")
print(True != True)
print(True != False)
print(False != True)
print(False != False)
print("---------------------")

print("Tabela negação (Unário)")
print(not True)
print(not False)
print("---------------------")

print("Cast com o operando bool")
print(bool(0))
print(bool(1))
print("---------------------")